### ISSUE TITLE
Mediathek does not work

### ISSUE THREAD

**Issue by Wikinaut** [YggdrasiI/plugin.video.simple_mediathek_de#7]
After installing a freshly compiled zip, it stalls. Logfile:
```
22:23:50.973 T:1630008304   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: [Errno 2] No such file or directory: '/home/osmc/.kodi/addons/plugin.video.simple_mediathek_de/root/bin/simple_mediathek'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.simple_mediathek_de/addon.py", line 1286, in <module>
                                                check_addon_status()
                                              File "/home/osmc/.kodi/addons/plugin.video.simple_mediathek_de/addon.py", line 566, in check_addon_status
                                                binary_setup(path)
                                              File "/home/osmc/.kodi/addons/plugin.video.simple_mediathek_de/chmod_binaries.py", line 16, in binary_setup
                                                stat_script = os.stat(script)
                                            OSError: [Errno 2] No such file or directory: '/home/osmc/.kodi/addons/plugin.video.simple_mediathek_de/root/bin/simple_mediathek'
                                            -->End of Python script error report<--
22:23:51.917 T:1958674432   ERROR: GetDirectory - Error getting plugin://plugin.video.simple_mediathek_de/
22:23:51.918 T:1958674432   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.simple_mediathek_de/) failed
```

Please can you check?

**Comment by YggdrasiI** [comment]
I' sorry for the very long delay of answering.

(DE) Entweder das Script root/bin/simple_mediathek ist in diesem Zip nicht enthalten gewesen oder Kodi hat es nicht mit entpackt. Bitte probiere es mit der neuen Variante aus, die ich unter https://github.com/YggdrasiI/plugin.video.simple_mediathek_de/releases/
veröffentlicht habe. Mit dieser kannst du nun auch direkt auf MediathekViewWeb zugreifen (jetzt endlich zum testen implementiert.) und Livestreams können auch aufgelistet werden.

**Comment by Wikinaut** [comment]
(DE) Entweder das Script root/bin/simple_mediathek ist in diesem Zip nicht enthalten gewesen ...

Na ja, dann funktioniert doch der make-Prozess nicht richtig, oder? Ich werde es demnächst nochmal probieren.
